server:
  port: 8081

spring:
  application:
    name: meeting-room-api
  h2:
    console:
      enabled: true
      
#Eureka Client   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/