server:
  port: 80

spring:
  application:
    name: meeting-room-web
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true

#Eureka Client   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/